name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: make build
    - name: Run tests
      run: swift test 2>&1 | xcpretty
